version: "3.8"

services:
  local_mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudmemedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin1234!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  flask_app:
    build: .
    restart: always
    depends_on:
      local_mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - .env  
    volumes:
      - .:/app  
    command: flask run --host=0.0.0.0 

volumes:
  db_data:
