"""Actualizar modelos para soportar etiquetas personalizadas y confianza

Revision ID: f3b47a46ac19
Revises: 1252837e0b3d
Create Date: 2025-02-09 21:45:05.603367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3b47a46ac19'
down_revision = '1252837e0b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etiquetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etiqueta', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('confianza', sa.Float(), nullable=True))
        batch_op.drop_index('nombre')
        batch_op.create_unique_constraint(None, ['etiqueta'])
        batch_op.drop_column('nombre')

    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=50), nullable=False))
        batch_op.alter_column('cargada',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.alter_column('cargada',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('usuario')

    with op.batch_alter_table('etiquetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('nombre', ['nombre'], unique=True)
        batch_op.drop_column('confianza')
        batch_op.drop_column('etiqueta')

    # ### end Alembic commands ###
